### ISSUE TITLE
passing parameter values through a file

### ISSUE THREAD

**Issue by rpietro** [Bart6114/infuser#5]
great package, but is it possible to pass parameter values in a file rather than in function? this would make it far easier in cases where a large number of values have to be instantiated in the template

**Comment by Bart6114** [comment]
@rpietro would #4 be sufficient for your use case? If not can you give me a concrete example? How would you structure the file?

**Comment by rpietro** [comment]
hey @Bart6114 this definitely helps, but I think that creating a csv would be easier for a really large number of fields, say 30 or more as in my case. for example, if you have a csv like:

a,1
b,2
c,3
...

a function within infuser taking a csv would parse the file using something like:

v1 <- read.csv("data.csv", header=FALSE)$V1
v2 <- read.csv("data.csv", header=FALSE)$V2
mylist  <- as.list(paste(v1,"=",v2))

**Comment by Bart6114** [comment]
As your example shows it is very easy to read in the csv yourself and convert it in a named list. I'm not going to implement this because I don't believe there is a consensus on what is the best text file structure for this is, nor want to specify the text file structure myself.

The extra code required is quite limited and, as is its up to the end-user, he retains flexibility in file structuring.

```
## extra needed code
mydata<-read.csv("data.csv", header=FALSE)
my_list <- as.list(mydata$V2)
names(my_list) <- mydata$V1

## the infuse code
infuse(template, my_list)
```

**Comment by rpietro** [comment]
makes sense, thanks
