### ISSUE TITLE
issues when using specific variable_identifier

### ISSUE THREAD

**Issue by datactix** [Bart6114/infuser#8]
Thanks for this great package.

I have an issue when using the parameter "variable_identifier" with the 'infuse' function. It does not seem to be taken into account.
However, function 'variables_requested' works as expected with specific parameter 'variable_identifier'. It seems that function 'infuse' does not pass along the parameter 'variable_identifier' to sub call to function 'variable_requested'.

Example:
my_sql<-"SELECT * FROM Customers WHERE Year = ${year} AND Month = ${month};"
variables_requested(my_sql, variable_identifier = c("\\${","}"), verbose = TRUE)
infuse(my_sql, year=2015, month=2, variable_identifier = c("\\${","}"), verbose=TRUE)

I hope it make sense.
best,

Vincent.

**Comment by Bart6114** [comment]
should be fixed in 89b8e1be6328728c443ff51ab200e365a10e0765
install from github for now (CRAN update pending)

please note in your example that you should escape the `$` sign with two backslashes:

```
my_sql<-"SELECT * FROM Customers WHERE Year = ${year} AND Month = ${month};"
variables_requested(my_sql, variable_identifier = c("\\${","}"), verbose = TRUE)
infuse(my_sql, year=2015, month=2, variable_identifier = c("\\${","}"), verbose=TRUE)
```

also (as a small suggestion) I like the following workflow :grin: :

```

"SELECT * FROM Customers WHERE Year = ${year} AND Month = ${month};" %>%
  infuse(year=2016, month=01, variable_identifier = c("\\${","}")) %>%
  RODBC::sqlQuery(my_connection, .)
```
Typing this I realise that it would be handy if you can set the `variable_identifier` somewhere so you don't have to retype it for every call to `infuse`...

**Comment by Bart6114** [comment]
Since  664bc2a you can use: 
```
options(variable_identifier = c("\\${","}"))

"SELECT * FROM Customers WHERE Year = ${year} AND Month = ${month};" %>%
 infuse(year=2016, month=01) %>%
 RODBC::sqlQuery(my_connection, .)
```

:smile:

**Comment by datactix** [comment]
thanks for the quick reply and fix.
great idea to provide variable_identifier as a persistent option.
